import { PALETTE } from '../palette';

export const pythonToolbox = {
  kind: 'categoryToolbox',
  contents: [
    // @blockly/toolbox-search — registered by blocklyPlugins.ts import
    { kind: 'search', name: 'Search', colour: '#090F11', contents: [] },

    // ── Hardware / connectivity ──────────────────────────────────────────────
    // Populated from catalog (mergeToolboxCategories in BlocklyEditor.tsx).
    { kind: 'category', name: 'Control',   colour: PALETTE.Control,   contents: [] },
    { kind: 'category', name: 'Sensors',  colour: PALETTE.Sensors,   contents: [] },
    { kind: 'category', name: 'Messaging', colour: PALETTE.Messaging, contents: [] },

    // ── Brick-level SBC categories ───────────────────────────────────────────
    // Placeholders for blocks generated by Python bricks.
    { kind: 'category', name: 'IoT',       colour: PALETTE.IoT,       contents: [] },
    { kind: 'category', name: 'Vision',    colour: PALETTE.Vision,    contents: [] },
    { kind: 'category', name: 'Audio',     colour: PALETTE.Audio,     contents: [] },
    { kind: 'category', name: 'Language',  colour: PALETTE.Language,  contents: [] },
    { kind: 'category', name: 'Storage',   colour: PALETTE.Storage,   contents: [] },
    { kind: 'category', name: 'Interface', colour: PALETTE.Interface, contents: [] },
    { kind: 'category', name: 'API',       colour: PALETTE.API,       contents: [] },

    // ── Programming constructs ───────────────────────────────────────────────
    {
      kind: 'category',
      name: 'Logic',
      colour: PALETTE.Logic,
      contents: [
        { kind: 'block', type: 'controls_if' },
        { kind: 'block', type: 'controls_switch_case' },
        { kind: 'block', type: 'logic_compare' },
        { kind: 'block', type: 'logic_operation' },
        { kind: 'block', type: 'logic_negate' },
        { kind: 'block', type: 'logic_boolean' },
        { kind: 'block', type: 'logic_null' },
        { kind: 'block', type: 'logic_ternary' },
      ],
    },
    {
      kind: 'category',
      name: 'Loops',
      colour: PALETTE.Loops,
      contents: [
        { kind: 'block', type: 'controls_repeat_ext' },
        { kind: 'block', type: 'controls_whileUntil' },
        { kind: 'block', type: 'controls_for' },
        { kind: 'block', type: 'controls_forEach' },
        { kind: 'block', type: 'controls_flow_statements' },
      ],
    },
    {
      kind: 'category',
      name: 'Mathematics',
      colour: PALETTE.Mathematics,
      contents: [
        { kind: 'block', type: 'math_number' },
        { kind: 'block', type: 'math_arithmetic' },
        { kind: 'block', type: 'math_single' },
        { kind: 'block', type: 'math_trig' },
        { kind: 'block', type: 'math_constant' },
        { kind: 'block', type: 'math_number_property' },
        { kind: 'block', type: 'math_round' },
        { kind: 'block', type: 'math_on_list' },
        { kind: 'block', type: 'math_modulo' },
        { kind: 'block', type: 'math_constrain' },
        { kind: 'block', type: 'math_random_int' },
        { kind: 'block', type: 'math_random_float' },
      ],
    },
    {
      kind: 'category',
      name: 'Text',
      colour: PALETTE.Text,
      contents: [
        { kind: 'block', type: 'text' },
        { kind: 'block', type: 'text_join' },
        { kind: 'block', type: 'text_append' },
        { kind: 'block', type: 'text_length' },
        { kind: 'block', type: 'text_isEmpty' },
        { kind: 'block', type: 'text_indexOf' },
        { kind: 'block', type: 'text_charAt' },
        { kind: 'block', type: 'text_getSubstring' },
        { kind: 'block', type: 'text_changeCase' },
        { kind: 'block', type: 'text_trim' },
        { kind: 'block', type: 'text_print' },
      ],
    },
    {
      kind: 'category',
      name: 'Lists',
      colour: PALETTE.Lists,
      contents: [
        { kind: 'block', type: 'lists_create_with' },
        { kind: 'block', type: 'lists_repeat' },
        { kind: 'block', type: 'lists_length' },
        { kind: 'block', type: 'lists_isEmpty' },
        { kind: 'block', type: 'lists_indexOf' },
        { kind: 'block', type: 'lists_getIndex' },
        { kind: 'block', type: 'lists_setIndex' },
        { kind: 'block', type: 'lists_getSublist' },
        { kind: 'block', type: 'lists_split' },
        { kind: 'block', type: 'lists_sort' },
        { kind: 'block', type: 'lists_reverse' },
      ],
    },
    {
      kind: 'category',
      name: 'Variables',
      colour: PALETTE.Variables,
      custom: 'VARIABLE',
    },
    {
      kind: 'category',
      name: 'Functions',
      colour: PALETTE.Functions,
      custom: 'PROCEDURE',
    },
  ],
};
