import { describe, it, expect } from 'vitest';
import { categorizeDefinitions, assembleScript } from './assembleScript';

describe('categorizeDefinitions', () => {
  it('sorts keys by prefix and handles variables separately', () => {
    const defs: Record<string, string> = {
      'variables': 'counter = None',
      'import_serial': 'import serial',
      'decl_handler': 'def on_data(args):\n    pass',
      'func_helper': 'def blink():\n    pass',
      'setup_init': 'ser = serial.Serial()',
    };
    const s = categorizeDefinitions(defs);
    expect(s.variables).toBe('counter = None');
    expect(s.imports).toContain('import serial');
    expect(s.imports).toContain('from arduino.app_utils import App');
    expect(s.declarations).toEqual(['def on_data(args):\n    pass']);
    expect(s.helpers).toEqual(['def blink():\n    pass']);
    expect(s.setup).toEqual(['ser = serial.Serial()']);
  });

  it('treats unprefixed import-looking values as imports', () => {
    const s = categorizeDefinitions({ 'from_math_import': 'from math import sqrt' });
    expect(s.imports).toContain('from math import sqrt');
  });

  it('treats other unprefixed values as declarations', () => {
    const s = categorizeDefinitions({ 'some_key': 'x = 42' });
    expect(s.declarations).toContain('x = 42');
  });
});

describe('assembleScript', () => {
  it('produces a valid script with all sections', () => {
    const defs: Record<string, string> = {
      'variables': 'counter = None',
      'import_serial': 'import serial',
      'setup_init': 'ser = serial.Serial()',
    };
    const out = assembleScript(defs, '    counter += 1', '    ', 'pass', new Set());

    expect(out).toContain('# Generated by Arduino App Lab');
    expect(out).toContain('import serial');
    expect(out).toContain('from arduino.app_utils import App');
    expect(out).toContain('counter = None');
    expect(out).toContain('ser = serial.Serial()');
    expect(out).toContain('def loop():');
    expect(out).toContain('global counter');
    expect(out).toContain('App.run(user_loop=loop)');
  });

  it('emits pass when loop body is empty', () => {
    const out = assembleScript({}, '', '    ', 'pass', new Set());
    expect(out).toContain('def loop():\n    pass');
  });

  it('injects global into decl_ function bodies that reference module vars', () => {
    const defs: Record<string, string> = {
      'variables': 'led = None',
      'decl_handler': 'def on_cmd(args):\n    led = not led',
    };
    const out = assembleScript(defs, '', '    ', 'pass', new Set());
    expect(out).toContain('def on_cmd(args):\n    global led\n    led = not led');
  });

  it('strips param var names from global lines in helpers', () => {
    const defs: Record<string, string> = {
      'variables': 'x = None',
      '%def_my_func': 'def my_func(a):\n    global x, a\n    x = a',
    };
    const out = assembleScript(defs, '', '    ', 'pass', new Set(['a']));
    expect(out).toContain('global x');
    expect(out).not.toMatch(/global x, a/);
  });
});
