import { describe, it, expect } from 'vitest';
import { categorizeDefinitions, assembleSketch } from './assembleSketch';

describe('categorizeDefinitions', () => {
  it('sorts keys by prefix into the correct buckets', () => {
    const defs: Record<string, string> = {
      'include_arduino': '#include <Arduino.h>',
      'import_wire': '#include <Wire.h>',
      'decl_pin': 'const int LED = 13;',
      'func_helper': 'void blink() { }',
      'setup_serial': 'Serial.begin(9600);',
    };
    const s = categorizeDefinitions(defs);
    expect(s.includes).toEqual(['#include <Arduino.h>', '#include <Wire.h>']);
    expect(s.declarations).toEqual(['const int LED = 13;']);
    expect(s.helpers).toEqual(['void blink() { }']);
    expect(s.setup).toEqual(['Serial.begin(9600);']);
  });

  it('skips empty values', () => {
    const s = categorizeDefinitions({ 'include_x': '', 'decl_y': '' });
    expect(s.includes).toEqual([]);
    expect(s.declarations).toEqual([]);
  });
});

describe('assembleSketch', () => {
  it('produces a valid sketch with all sections', () => {
    const defs: Record<string, string> = {
      'include_a': '#include <Servo.h>',
      'decl_pin': 'Servo myServo;',
      'setup_attach': 'myServo.attach(9);',
    };
    const out = assembleSketch(defs, '  myServo.write(90);', '  ');

    expect(out).toContain('// Generated by Arduino App Lab');
    expect(out).toContain('#include <Servo.h>');
    expect(out).toContain('Servo myServo;');
    expect(out).toContain('void setup() {\n  myServo.attach(9);\n}');
    expect(out).toContain('void loop() {\n  myServo.write(90);\n}');
  });

  it('produces empty setup/loop when nothing is provided', () => {
    const out = assembleSketch({}, '', '  ');
    expect(out).toContain('void setup() {\n}');
    expect(out).toContain('void loop() {\n}');
  });

  it('omits section headers for empty sections', () => {
    const out = assembleSketch({}, '  foo();', '  ');
    expect(out).not.toContain('// --- Includes ---');
    expect(out).not.toContain('// --- Declarations ---');
  });
});
