const HEADER = '// Generated by Arduino App Lab — do not edit.';

interface SketchSections {
  includes: string[];
  declarations: string[];
  helpers: string[];
  setup: string[];
}

export function categorizeDefinitions(definitions: Record<string, string>): SketchSections {
  const sections: SketchSections = { includes: [], declarations: [], helpers: [], setup: [] };
  for (const [key, value] of Object.entries(definitions)) {
    if (!value) continue;
    if (key.startsWith('include_') || key.startsWith('import_')) sections.includes.push(value);
    else if (key.startsWith('decl_')) sections.declarations.push(value);
    else if (key.startsWith('func_')) sections.helpers.push(value);
    else if (key.startsWith('setup_')) sections.setup.push(value);
  }
  return sections;
}

function indent(code: string, prefix: string): string {
  return code.split('\n').map(line => (line.length ? prefix + line : line)).join('\n');
}

function wrapFunction(signature: string, body: string, indentStr: string): string {
  const trimmed = body.replace(/\n+$/, '');
  const indented = trimmed ? indent(trimmed, indentStr) : '';
  return indented ? `${signature} {\n${indented}\n}` : `${signature} {\n}`;
}

export function assembleSketch(
  definitions: Record<string, string>,
  loopBody: string,
  indentStr: string,
): string {
  const s = categorizeDefinitions(definitions);
  const sections: string[] = [];

  sections.push(`${HEADER}\n// ${new Date().toISOString()}`);
  if (s.includes.length) sections.push('// --- Includes ---\n' + s.includes.join('\n'));
  if (s.declarations.length) sections.push('// --- Declarations ---\n' + s.declarations.join('\n'));
  if (s.helpers.length) sections.push('// --- Helper functions ---\n' + s.helpers.join('\n\n'));
  sections.push(wrapFunction('void setup()', s.setup.join('\n\n'), indentStr));

  // loopBody arrives pre-indented from the generator
  const loopContent = loopBody.replace(/\n+$/, '');
  sections.push(loopContent ? `void loop() {\n${loopContent}\n}` : 'void loop() {\n}');

  return sections.join('\n\n') + '\n';
}
